# Generated by Django 3.0.2 on 2020-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
