# Generated by Django 2.2.4 on 2020-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
