# Generated by Django 3.0.2 on 2020-02-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20200210_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imgpicture',
            new_name='image',
        ),
    ]
