# Generated by Django 3.0.2 on 2020-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20200210_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
