# Generated by Django 3.0.2 on 2020-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_topics_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pdflink',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
