# Generated by Django 3.0.2 on 2020-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_images_pdflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='topics',
            name='temail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
