# Generated by Django 3.0.2 on 2020-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='emailw',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userw',
            field=models.CharField(default='', max_length=100),
        ),
    ]
